In [50]:
import cv2
import numpy as np

img_origine = cv2.imread('couleur.jpg')
img = img_origine.copy()

In [51]:
px = img[100,100]
print(px)

[210 194 178]


In [52]:
blue = img[100,100,2]
print(blue)

178


In [53]:
img[100,100] = [255,255,255]

In [54]:
print(img[100, 100, 2])

255


In [55]:
img.item(10,10,2)


230

In [56]:
img.itemset((10,10,2),100)
img.item(10,10,2)

100

In [57]:
print(img.shape)

(1359, 1812, 3)


In [58]:
print(img.size)

7387524


In [59]:
print(img.dtype)

uint8


In [60]:
!ls

Untitled.ipynb couleur.jpg


In [61]:
b,g,r = cv2.split(img)

In [62]:
sum = 0.2125 * b + 0.7154 * g + 0.0721* r
print(sum)

[[233.7933 233.7933 234.7933 ...  44.7627  40.7627  38.7627]
 [230.7933 231.7933 232.7933 ...  49.7627  45.7627  43.7627]
 [227.7933 228.7933 229.7933 ...  47.7627  43.7627  42.7627]
 ...
 [ 83.0582  79.0582  82.4832 ... 103.2151  98.2151  92.2151]
 [ 79.6294  78.6294  81.0582 ...  99.993   94.993   88.993 ]
 [ 73.2044  78.6294  83.6294 ...  94.5584  88.5584  81.5584]]


In [63]:
sum = np.around(sum, decimals=-1)
img = sum
print(img)

[[230. 230. 230. ...  40.  40.  40.]
 [230. 230. 230. ...  50.  50.  40.]
 [230. 230. 230. ...  50.  40.  40.]
 ...
 [ 80.  80.  80. ... 100. 100.  90.]
 [ 80.  80.  80. ... 100.  90.  90.]
 [ 70.  80.  80. ...  90.  90.  80.]]


In [64]:
cv2.imwrite('gris.jpg', img)

True